# Generated by Django 3.2.9 on 2021-11-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', unique=True)),
                ('ProfilePicture', models.FilePathField(null=True, path='./static/img/patients/')),
                ('FirstName', models.CharField(max_length=65)),
                ('LastName', models.CharField(max_length=65)),
                ('Address', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=200)),
                ('DOB', models.DateField(null=True)),
                ('BloodGroup', models.CharField(max_length=5)),
            ],
        ),
    ]
