# Generated by Django 3.2.9 on 2021-11-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='ProfilePicture',
            field=models.ImageField(null=True, upload_to='patients/profile_pictures/'),
        ),
    ]
