# Generated by Django 3.2.8 on 2021-11-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patients_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='ProfilePicture',
            field=models.ImageField(default='patients/profile_images/profile-default.png', null=True, upload_to='patients/profile_pictures/'),
        ),
    ]
