# Generated by Django 3.1.4 on 2021-11-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211113_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocProfile',
        ),
    ]
