# Generated by Django 3.2.9 on 2021-11-24 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_patients_profilepicture'),
        ('doctor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppointmentID', models.CharField(max_length=15)),
                ('AppointmentDate', models.DateField()),
                ('AppointmentFee', models.FloatField(blank=True, default=0)),
                ('Remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('Status', models.CharField(default='Pending', max_length=50)),
                ('Document', models.FileField(blank=True, null=True, upload_to='patients/appointment-documents/')),
                ('DoctorUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.docprofile')),
                ('PatientUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
            ],
        ),
    ]
